//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychet_racxodov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vid_racxodov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vid_racxodov()
        {
            this.Racxod = new HashSet<Racxod>();
        }
    
        public int kod_vida { get; set; }
        public string name { get; set; }
        public string opicanie { get; set; }
        public Nullable<double> predel_norma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racxod> Racxod { get; set; }
    }
}
